# Generated by Django 4.1.7 on 2023-03-25 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0002_task_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="body",
            field=models.TextField(blank=True, null=True),
        ),
    ]
